### PR TITLE
Update AVS device SDK to version 3.0.0

### LINKED ISSUE #85: Updates to match v3.0.0
Update to incorporate the changes in the alexa/avs-device-sdk v3.0.0 release.

### PR DESCRIPTION
**Pull request by lucianomartin**
99% of the changes in this PR are due to updates in the 'alexa' fork, where the version has changed from v1.26.0 to v3.0.0.
To review the changes related to the XMOS devices, I recommend to use the comparison below:
https://github.com/alexa/avs-device-sdk/compare/master...lucianomartin:avs-device-sdk:feature/alexa-v3.0.0?expand=1  
Most of the files are ported from the 'xmos' version v1.26.0.0, for example the HID and GPIO keyword detector files. I would pay special attention to the pi.sh and setup.sh scripts.

The XVF3615-UA and XVF3615-INT need special handling of the KWD classes.
This PR removes all the code related to the following defines/features (see https://github.com/xmos/vocalfusion-avs-setup/issues/69):
  - PI_HAT_CTRL: used for XVF3610
  - sales demo for XVF3510
  - SENSORY_OP_POINT and other Sensory KWD features
  -  XMOS_AVS_TESTS: this feature requires a KWD on the host, such as Sensory
  
 I tested the setups for:
    - XVF3610-INT
    - XVF3610-UA
    - XVF3615-INT
    - XVF3615-UA
    
  Part of https://github.com/xmos/vocalfusion-avs-setup/issues/69
  Closes #85

### CODE REVIEW

**Comment by mbanth** [comment]
Given the difficulties of finding a specific file in the review, I will list my comments here.  I have only reviewed the files in [the comparison](https://github.com/alexa/avs-device-sdk/compare/master...lucianomartin:avs-device-sdk:feature/alexa-v3.0.0?expand=1) provided by @lucianomartin.  Thanks to him for making this comparison available.  Files I do not mention are okay.

In [GPIOKeywordDetector.h](https://github.com/alexa/avs-device-sdk/compare/master...lucianomartin:avs-device-sdk:feature/alexa-v3.0.0?expand=1#diff-d604a3e930e06e6f312141a2a6eadbdc42bb98aa1cfc2b93525baff15f192baf), remove the sentence on lines 1 & 2 that applies the XMOS Public license.  Also modify the XMOS copyright to state `Modifications  (c) 2021-2022 XMOS Limited`.  Please make this set of changes in each file that mentions the XMOS Public license and the Apache license.  These two license are incompatible with one another according to @tomblackie-xmos.

In [KeywordDetector.cmake](https://github.com/alexa/avs-device-sdk/compare/master...lucianomartin:avs-device-sdk:feature/alexa-v3.0.0?expand=1#diff-a8a84c26f23c8766d7b9c8f8cec00637db4d0a7e2bce62e85e28d2ecfa76eeda), lines 121 - 123 mention `PI_HAT_CTRL`, but the description of the PR says that all code related to PI_HAT_CTRL has been removed.

**Review by mbanth — CHANGES_REQUESTED** [review]
See [comment](https://github.com/xmos/avs-device-sdk/pull/87#issuecomment-1614482353)

**Comment by lucianomartin** [comment]
> See [comment](https://github.com/xmos/avs-device-sdk/pull/87#issuecomment-1614482353)

@mbanth, the requested changes have been included in https://github.com/xmos/avs-device-sdk/pull/87/commits/c436a358405e1d5fe80cf19da160bd0d2aee7c3c

**Review by mbanth — APPROVED** [review]
The change I have reviewed look okay.  I note, in passing, that some copyright date ranges were changes from `2022` to `2021-2023` which may cause a problem with one of the checking scripts.

**Pull request merged**
